config/routes.rb
Quiztest::Application.routes.draw do

 
  resources :ideas
resources :quizzes

  resources :questions
   
  get "quiz/index"
  
  post "quiz/start"

  get "quiz/question"
  
  post "quiz/question"

  post "quiz/answer"

  get "quiz/end"
  
  post "choices/create"
  
  post "choices/destroy"

root :to => redirect('/homes')

devise_for :users
 

  match ':controller(/:action(/:id))', :via => :get
   resources :homes
 get  "homes/index"
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  attr_accessible :answer, :name, :question
  # mount_uploader :picture, PictureUploader
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  layout "homelay"
  before_filter :authenticate_user!
  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ideas }
    end
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea = Idea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/new
  # GET /ideas/new.json
  def new
    @idea = Idea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(params[:idea])

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render json: @idea, status: :created, location: @idea }
      else
        format.html { render action: "new" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ideas/1
  # PUT /ideas/1.json
  def update
    @idea = Idea.find(params[:id])

    respond_to do |format|
      if @idea.update_attributes(params[:idea])
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= form_for @idea, :html => {:multipart => true} do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Title of this Question" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
  <%= f.file_field :picture, "Add picture" %>
  </div>
  <div class="field">
    <%= f.label :question %><br />
    <%= f.text_area :question %>
  </div>
  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_area :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<div style="text-align:center; font-family: Courier; font-size: 34px">Share your knowledge. Gain More!!</div>
<div style="text-align:center;">
<h1 style="font-family: monotype corsiva; ">Have New Questions?</h1>
<ul>
  <br />
        <p style="font-family: calibri;font-size: 24px;" >
          <a href="/questions" >Create Quizzes</a>....</p>

</ul>
<div style="font-size: 35px;">
<table>
  <br />
<% @ideas.each do |idea| %>
  <tr>
    <td><%= idea.name %></td>
    <td><%= idea.question %></td>
  <!--fecth the answers  <td><%= idea.answer %></td> -->
    <td><%= link_to 'Show', idea %></td>
    <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
    <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

</div>
</div>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<table>
	<tr>
  <th>Name:</th>
<td>  <%= @idea.name %>
</td></tr>

	<tr>
  <th>Picture</th>
<td> 
<!-- <%= image_tag(@idea.picture_url,# :width => 600) if @idea.picture.present? %> --> 
</td></tr>

<tr>
  <th>Question:</th>
 <td> <%= @idea.question %></td>
</tr>

<p>
  <b>Answer:</b>
  <%= @idea.answer %>
</p>


<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>